name: be_energised
description: This app is used to track one's energy level every day and provides data about how they spend their energy in that day.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.7
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/battery.png"
  web:
    generate: true
    image_path: "assets/icons/battery.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/activity_icons/
    - assets/background/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf
        - asset: assets/fonts/Poppins-Bold.otf
          weight: 700
